version: '3.8'

services:
  backend:
    image: mesbahtanvir/ishkul-backend:latest
    ports:
      - "8080:8080"
    networks:
      - ishkul-network

  frontend:
    image: mesbahtanvir/ishkul-react-app:latest
    ports:
      - "80:80"
    networks:
      - ishkul-network

networks:
  ishkul-network:
    driver: bridge
