version: '3.8'

services:
  backend:
    build: ./../backend
    working_dir: ./../backend
    ports:
      - "8080:8080"
    environment:
      MONGODB_PROTOCOL: "mongodb"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"

    networks:
      - ishkul-network
    depends_on:
      - mongodb

  frontend:
    build: ./../web/ishkul-react-app
    working_dir: ./..web/ishkul-react-app

    ports:
      - "80:80"
    networks:
      - ishkul-network

  contributor:
    build: ./../web/ishkul-contributor-app
    working_dir: ./..web/ishkul-contributor-app

    ports:
      - "3000:3000"
    networks:
      - ishkul-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - ishkul-network

volumes:
  dbdata6:

networks:
  ishkul-network:
    driver: bridge
