version: '3.8'

services:
  backend:
    image: mesbahtanvir/ishkul-backend:latest
    ports:
      - "8080:8080"
    environment:
      MONGODB_PROTOCOL: "mongodb"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"

    networks:
      - ishkul-network
    depends_on:
      - mongodb

  frontend:
    image: mesbahtanvir/ishkul-react-app:latest

    ports:
      - "80:80"
    networks:
      - ishkul-network

  contributor:
    image: mesbahtanvir/ishkul-contributor-app:latest

    ports:
      - "3000:3000"
    networks:
      - ishkul-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - ishkul-network

volumes:
  dbdata6:

networks:
  ishkul-network:
    driver: bridge
