version: '3.8'

services:
  backend:
    image: mesbahtanvir/ishkul-backend:latest
    environment:
      MONGODB_SCHEME: "mongodb"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
    ports:
      - "8080:8080"
    networks:
      - ishkul-network
    depends_on:
      - mongodb

  ishkul-web:
    image: mesbahtanvir/ishkul-web:latest
    ports:
      - "80:80"
    networks:
      - ishkul-network

  ishkul-app:
    image: mesbahtanvir/ishkul-app:latest
    ports:
      - "3000:3000"
    networks:
      - ishkul-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - ishkul-network

volumes:
  dbdata6:

networks:
  ishkul-network:
    driver: bridge
