version: "3.8"

services:
  backend:
    image: mesbahtanvir/ishkul-backend:latest
    environment:
      APP_ENV: "production"
      MONGODB_SCHEME: "mongodb"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      # Add Redis environment variables here
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "8080:8080"
    networks:
      - ishkul-network
    depends_on:
      - mongodb
      - redis # Add dependency on Redis

  ishkul-web:
    image: mesbahtanvir/ishkul-web:latest
    ports:
      - "80:80"
    networks:
      - ishkul-network

  ishkul-app:
    image: mesbahtanvir/ishkul-app:latest
    ports:
      - "3000:3000"
    networks:
      - ishkul-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - ishkul-network

  # Define the Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ishkul-network
    volumes:
      - redisdata:/data

volumes:
  dbdata6:
  redisdata: # Define a volume for Redis data

networks:
  ishkul-network:
    driver: bridge
